language: ruby
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
rvm:
  - 2.1.5
script:
  - bundle exec rubocop
  - bundle exec ruby manuscript/lib/driver.rb
  - bundle exec ruby manuscript/lib/element.rb
  - bundle exec ruby manuscript/lib/headless_phantomjs.rb
  - bundle exec ruby manuscript/lib/installation.rb
  - bundle exec ruby manuscript/lib/quick_start.rb
  - bundle exec ruby manuscript/lib/headless_block_mode.rb
  - bundle exec ruby manuscript/lib/headless_object_mode.rb
