language: ruby
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
rvm:
  - 2.1.0
script:
  - bundle exec ruby lib/quick_start_1.rb
  - bundle exec ruby lib/quick_start_2.rb
